#-------------------------------
# General Site Settings
title: Otavio's Portfolio
logo: logo.svg # You can add own logo.
description: Personal data science Portfolio


#-------------------------------
# Author Settings
author:
  name: Otávio Guerra
  image: 01.jpg
  say-hello: Hello, I’m <strong>Otávio Guerra</strong>
  bio: This blog has the purpose of showing my skills in the <strong>Data Science</strong> field, mostly through personal projects. My main areas of interest at the moment are <strong>Big Data</strong>, <strong>Time Series Analysis/forecasting</strong> and <strong>Explainable AI</strong>. Currently, I work as a Data Scientist and Data Science tutor in Ceará, Brazil.


#-------------------------------
# Contact links


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: Author # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile:  # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e